baseURL: https://mihavlic.github.io/
languageCode: en-us
title: Function viewer
theme: hugo-book

params:
  BookTheme: auto
  BookServiceWorker: true
  BookSearch: true
  BookServiceWorker: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
